# @rolldown/binding-linux-arm64-gnu — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1nfkf9xzrvnw0ppiv55ns9c6z3i62hyb01fxrjmdk7frmlr56864";
    };
  };
}
