# @rolldown/binding-linux-arm-gnueabihf — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0zkjnv83glagqhwrqrrx0w290vkgiwkk5ayj8nfrgvf3n5vw77nj";
    };
  };
}
