# @rolldown/binding-wasm32-wasi — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1gfjm16qlxl8wm07zsjxv6xfig9681s1xlxafj85fqb2lv6s6p25";
    };
  };
}
