# @rolldown/binding-win32-x64-msvc — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "13r7kisfpas5lmgb1kapckkml83n92778k903yvy2735n3695bxs";
    };
  };
}
