# @rolldown/binding-linux-x64-gnu — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0xfricdk58sddqa4fslm529ppg6f0f53s4y239sgqlh98am5z63g";
    };
  };
}
