# @rolldown/binding-linux-arm64-musl — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1f7m7h38iix5bdmx9001vpfd9dbjkj1p68cikr8pa21qdvvhyjrs";
    };
  };
}
