# @rolldown/binding-freebsd-x64 — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1r5j3dgqf973fqsxnqzkhn78n42jlrjl49gdza52vc5p18gy2v6g";
    };
  };
}
