# @rolldown/binding-linux-x64-musl — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "1wnqw11qaipj7psfmq7f291722rwqzplszppsl1yq9zmfsgaswwn";
    };
  };
}
