# @rolldown/binding-darwin-x64 — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "0n26nhb911h620l1pnpv70bzs4da7rfnsi6yryi4abslncl4d8l4";
    };
  };
}
