# @rolldown/binding-openharmony-arm64 — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "15zr76nb2zs0x0j4jh7fhn1v8zhvlffm9pbacbslvnpxdcr1yzhj";
    };
  };
}
