# @rolldown/binding-win32-arm64-msvc — generated by onix. Do not edit.
{
  "1.0.0-rc.3" = {
    version = "1.0.0-rc.3";
    source = {
      type = "tarball";
      remotes = [ "https://registry.npmjs.org" ];
      sha256 = "14nbcazah1i2x4znwimg2wkxfb7rjjfkqv5rn8gvs4byi3ba0l4a";
    };
  };
}
